GET http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2luYSIsImlhdCI6MTY1NTMwMTE4MywiZXhwIjoxNjU1MzAxMjEzfQ.uuQsjK4K8GGWCge3zDcYihIIj2-8o_fnfHnYAGE3PX0

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Gina"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2luYSIsImlhdCI6MTY1NTMwMTE4MywiZXhwIjoxNjU1MzA0NzgzfQ.HjtS4mUpIGGeQlEBI2mN3gTQk2zaYsak_RkgpqyzFhM"
}