GET http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2luYSIsImlhdCI6MTY1NTI5NDQ1NCwiZXhwIjoxNjU1Mjk0NDg0fQ.rgqb9crJ2D6Y10TXucMsQSBld872HTC2T999tFCp9BI

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Gina"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2luYSIsImlhdCI6MTY1NTI5NDQ0MSwiZXhwIjoxNjU1Mjk4MDQxfQ.AJGhiCeHCaZQjKz4FIjnsUO5e2zGCKPcrm_Ypenwn0A"
}